INHERIT: nav.yml

site_name: Unsplash Developers
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  custom_dir: overrides
  palette:
    primary: custom
    accent: custom
markdown_extensions:
  - attr_list